# Generated by Django 4.0.3 on 2022-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('psize', models.CharField(max_length=10)),
                ('pcolor', models.CharField(max_length=20)),
                ('pdetail', models.CharField(max_length=200)),
                ('pimage', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=200)),
                ('user_contact', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=100)),
                ('c_Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
