# Generated by Django 4.0.3 on 2022-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
